"""initial schema

Revision ID: 59f76ad1447c
Revises:
Create Date: 2026-09-10 02:48:20.790897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59f76ad1447c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starter_id", sa.BigInteger(), nullable=False),
        sa.Column("anilist_id", sa.Integer(), nullable=True),
        sa.Column("title_romaji", sa.String(length=255), nullable=True),
        sa.Column("title_english", sa.String(length=255), nullable=True),
        sa.Column("title_native", sa.String(length=255), nullable=True),
        sa.Column("synonyms", sa.JSON(), nullable=True),
        sa.Column("original_file_id", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SETUP", "ACTIVE", "WON", "UNSOLVED", name="gamestatus"),
            nullable=False,
        ),
        sa.Column(
            "current_stage", sa.Enum("X10", "X8", "X5", "X2", name="pixelstage"), nullable=True
        ),
        sa.Column("wrong_guess_count", sa.Integer(), nullable=False),
        sa.Column("winner_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("scheduled_end_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["starter_id"],
            ["players.telegram_user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["players.telegram_user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "turn_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("next_starter_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["next_starter_id"],
            ["players.telegram_user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turn_state")
    op.drop_table("games")
    op.drop_table("players")
    # ### end Alembic commands ###
