"""add total_guess_count to games

Revision ID: a5ef10f74e63
Revises: ceb97aa09d23
Create Date: 2026-09-10 05:02:51.287718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5ef10f74e63"
down_revision: str | Sequence[str] | None = "ceb97aa09d23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required: adding a NOT NULL column to a table that
    # already has rows (the live games table does) fails on MariaDB
    # otherwise. Existing rows backfill to 0, same as the model default.
    op.add_column(
        "games",
        sa.Column("total_guess_count", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "total_guess_count")
    # ### end Alembic commands ###
